import { createSlice, nanoid } from "@reduxjs/toolkit";

import Iphone14pro from "../assets/Iphone14 pro.jpg";
import Iphone13 from "../assets/iphone13 pro.jfif";
import Iphone13_max from "../assets/iphone13max.jfif";
import samsung1 from "../assets/samsung1.jfif";
import samsung2 from "../assets/samsung2.jfif";
import samsung from "../assets/Samsung.jpg";

import Shoe from "../assets/shoe.jfif";
import Shoe3 from "../assets/shoe3.jfif";
import Shoe2 from "../assets/shoe2.jfif";

import female_trouser from "../assets/female_trouser.jfif";
import male_trouser from "../assets/male_trouser.jfif";
import male_trouser1 from "../assets/male_trouser3.jfif";

import male_shirt from "../assets/male_shirt.jfif";
import male_shirt1 from "../assets/male_shirt1.jfif";
import male_shirt2 from "../assets/male_shirt2.jfif";

import Shoe1 from "../assets/shoe1.jfif";

export const Products = [
  {
    _id: nanoid(),
    Name: "Iphone 14pro max",
    Slug: "Apple",
    Image: Iphone14pro,
    Brand: "Apple",
    Price: "1500000",
    DisPrice: "1200000",
    Rating: 5,
    Instouck: 8,
    Review: 20,
    Description: "Iphone 14pro max,  new",
    Category: "Phone",
  },
  {
    _id: nanoid(),
    Name: "Sleve Shirt",
    Slug: "JoeBryan",
    Image: male_shirt,
    Brand: "JoeBryan",
    Price: "15000",
    DisPrice: "10000",
    Rating: 3,
    Instouck: 4,
    Review: 10,
    Description: "male quality shirt",
    Category: "Fashion",
  },
  {
    _id: nanoid(),
    Name: "Trouser",
    Slug: "Niki",
    Image: female_trouser,
    Brand: "Niki",
    Price: "25000",
    DisPrice: "20000",
    Rating: 3,
    Instouck: 13,
    Review: 25,
    Description: "female quality trouser",
    Category: "Fashion",
  },
  {
    _id: nanoid(),
    Name: "Shoe snikers",
    Slug: "Niki-shoe",
    Image: Shoe,
    Brand: "Niki",
    Price: "1200",
    DisPrice: "1000",
    Rating: 3,
    Instouck: 30,
    Review: 10,
    Description: "",
    Category: "Fashion",
  },
  {
    _id: nanoid(),
    Name: "Shoe snikers",
    Slug: "Niki-shoes",
    Image: Shoe3,
    Brand: "Niki",
    Price: "250",
    DisPrice: "200",
    Rating: 3,
    Instouck: 4,
    Review: 10,
    Description: "",
    Category: "Fashion",
  },
  {
    _id: nanoid(),
    Name: "Trouser",
    Slug: "Niki",
    Image: male_trouser,
    Brand: "Niki",
    Price: "25000",
    DisPrice: "20000",
    Rating: 3,
    Instouck: 3,
    Review: 25,
    Description: "female quality trouser",
    Category: "Fashion",
  },
  {
    _id: nanoid(),
    Name: "Sleve Shirt",
    Slug: "sleve",
    Image: male_shirt1,
    Brand: "JoeBryan",
    Price: "15000",
    DisPrice: "10000",
    Rating: 3.5,
    Instouck: 2,
    Review: 10,
    Description: "male quality shirt",
    Category: "Fashion",
  },
  {
    _id: nanoid(),
    Name: "samsung",
    Slug: "samsung1",
    Image: samsung1,
    Brand: "samsung1",
    Price: "1500000",
    DisPrice: "1200000",
    Rating: 5,
    Instouck: 8,
    Review: 20,
    Description: "samsung1,  new",
    Category: "Phone",
  },
  {
    _id: nanoid(),
    Name: "Iphone13",
    Slug: "Apple",
    Image: Iphone13,
    Brand: "Apple",
    Price: "1500000",
    DisPrice: "1200000",
    Rating: 5,
    Instouck: 8,
    Review: 20,
    Description: "Iphone 14pro max,  new",
    Category: "Phone",
  },
  {
    _id: nanoid(),
    Name: "Trouser",
    Slug: "jeans",
    Image: male_trouser1,
    Brand: "Niki",
    Price: "25000",
    DisPrice: "20000",
    Rating: 3,
    Instouck: 8,
    Review: 25,
    Description: "female quality trouser",
    Category: "Fashion",
  },
  {
    _id: nanoid(),
    Name: "Shoe snikers",
    Slug: "snikers",
    Image: Shoe2,
    Brand: "Niki",
    Price: "50",
    DisPrice: "40",
    Rating: 3,
    Instouck: 8,
    Review: 10,
    Description: "",
    Category: "Fashion",
  },
  {
    _id: nanoid(),
    Name: "Sleve Shirt",
    Slug: "Sleve Shirt",
    Image: male_shirt2,
    Brand: "JoeBryan",
    Price: "15000",
    DisPrice: "10000",
    Rating: 3,
    Instouck: 8,
    Review: 10,
    Description: "male quality shirt",
    Category: "Fashion",
  },
  {
    _id: nanoid(),
    Name: "Sleve Shirt",
    Slug: "Verncial",
    Image: Shoe1,
    Brand: "JoeBryan",
    Price: "1000",
    DisPrice: "8000",
    Rating: 3.5,
    Instouck: 18,
    Review: 20,
    Description: "male quality shoe",
    Category: "Fashion",
  },
  {
    _id: nanoid(),
    Name: "Samsung s20",
    Slug: "Samsung",
    Image: samsung2,
    Brand: "JoeBryan",
    Price: "15000",
    DisPrice: "10000",
    Rating: 3.5,
    Instouck: 18,
    Review: 20,
    Description: "Samsung Andriod",
    Category: "Phone",
  },
  {
    _id: nanoid(),
    Name: "Iphone13_max",
    Slug: "Iphone",
    Image: Iphone13_max,
    Brand: "JoeBryan",
    Price: "150000",
    DisPrice: "130000",
    Rating: 4.5,
    Instouck: 10,
    Review: 25,
    Description: "Iphone 13 pro max",
    Category: "Phone",
  },
];
